/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface DiceContract extends Truffle.Contract<DiceInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<DiceInstance>;
}

type AllEvents = never;

export interface DiceInstance extends Truffle.ContractInstance {
  changeRandomFactor: {
    (
      num: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      num: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      num: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      num: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  random(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  min(
    a: number | BN | string,
    b: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  max(
    a: number | BN | string,
    b: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  methods: {
    changeRandomFactor: {
      (
        num: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        num: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        num: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        num: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    random(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    min(
      a: number | BN | string,
      b: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    max(
      a: number | BN | string,
      b: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
