/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { DiceContract } from "./Dice";
import { DiceCommonContract } from "./DiceCommon";
import { DiceInterfaceContract } from "./DiceInterface";
import { DiceSpecContract } from "./DiceSpec";
import { FactoryContract } from "./Factory";
import { GameContractContract } from "./GameContract";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Dice"): DiceContract;
      require(name: "DiceCommon"): DiceCommonContract;
      require(name: "DiceInterface"): DiceInterfaceContract;
      require(name: "DiceSpec"): DiceSpecContract;
      require(name: "Factory"): FactoryContract;
      require(name: "GameContract"): GameContractContract;
    }
  }
}

export { DiceContract, DiceInstance } from "./Dice";
export { DiceCommonContract, DiceCommonInstance } from "./DiceCommon";
export { DiceInterfaceContract, DiceInterfaceInstance } from "./DiceInterface";
export { DiceSpecContract, DiceSpecInstance } from "./DiceSpec";
export { FactoryContract, FactoryInstance } from "./Factory";
export { GameContractContract, GameContractInstance } from "./GameContract";
