/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface DiceSpec extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): DiceSpec;
  clone(): DiceSpec;
  methods: {
    changeRandomFactor(
      num: number | string | BN
    ): NonPayableTransactionObject<void>;

    max(
      a: number | string | BN,
      b: number | string | BN
    ): NonPayableTransactionObject<string>;

    min(
      a: number | string | BN,
      b: number | string | BN
    ): NonPayableTransactionObject<string>;

    random(): NonPayableTransactionObject<string>;

    roll(bet: number | string | BN): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
