/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Dice } from "./Dice";
export type { DiceCommon } from "./DiceCommon";
export type { DiceInterface } from "./DiceInterface";
export type { DiceSpec } from "./DiceSpec";
export type { Factory } from "./Factory";
export type { GameContract } from "./GameContract";
